version: "3"

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none

  format:
    desc: format code
    cmds:
      - uv run ruff format src
  lint:
    desc: lint code
    cmds:
      - uv run ruff check --fix src

  qualify:
    desc: qualify code
    cmds:
      - task format
      - task lint

